[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "streamvis"
version = "0.1.0"
description = "Interactive visualizations of streaming data using Bokeh"
authors = [{name="Henry Bigelow", email="hrbigelow@gmail.com"}]
dependencies = [
  "tornado",
  "numpy",
  "fire",
  "bokeh"
]

[project.scripts]
streamvis_server = "streamvis.server:run"

[tool.setuptools]
packages = ["streamvis"]



