[tool.poetry]
name = "streamvis"
version = "0.1.0"
description = "Interactive visualizations of streaming data using Bokeh"
authors = ["Henry Bigelow <hrbigelow@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
bokeh = "^2.4.3"
fire = "^0.5.0"
numpy = "^1.1.6"
tornado = "^6.1"

[tool.poetry.group.dev.dependencies]
setuptools = "^67.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
