# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from streamvis.v1 import data_pb2 as streamvis_dot_v1_dot_data__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in streamvis/v1/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeOrGetScope = channel.unary_unary(
                '/streamvis.v1.Service/MakeOrGetScope',
                request_serializer=streamvis_dot_v1_dot_data__pb2.GetScopeRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.GetScopeResponse.FromString,
                _registered_method=True)
        self.DeleteScope = channel.unary_unary(
                '/streamvis.v1.Service/DeleteScope',
                request_serializer=streamvis_dot_v1_dot_data__pb2.DeleteScopeRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.DeleteScopeResponse.FromString,
                _registered_method=True)
        self.MakeOrGetSeries = channel.unary_unary(
                '/streamvis.v1.Service/MakeOrGetSeries',
                request_serializer=streamvis_dot_v1_dot_data__pb2.GetSeriesRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.GetSeriesResponse.FromString,
                _registered_method=True)
        self.AppendToSeries = channel.unary_unary(
                '/streamvis.v1.Service/AppendToSeries',
                request_serializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesResponse.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeOrGetScope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeOrGetSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendToSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeOrGetScope': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeOrGetScope,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.GetScopeRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.GetScopeResponse.SerializeToString,
            ),
            'DeleteScope': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScope,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.DeleteScopeRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.DeleteScopeResponse.SerializeToString,
            ),
            'MakeOrGetSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeOrGetSeries,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.GetSeriesRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.GetSeriesResponse.SerializeToString,
            ),
            'AppendToSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendToSeries,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamvis.v1.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamvis.v1.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeOrGetScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/MakeOrGetScope',
            streamvis_dot_v1_dot_data__pb2.GetScopeRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.GetScopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/DeleteScope',
            streamvis_dot_v1_dot_data__pb2.DeleteScopeRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.DeleteScopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeOrGetSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/MakeOrGetSeries',
            streamvis_dot_v1_dot_data__pb2.GetSeriesRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.GetSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendToSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/AppendToSeries',
            streamvis_dot_v1_dot_data__pb2.AppendToSeriesRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.AppendToSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
