# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from streamvis.v1 import data_pb2 as streamvis_dot_v1_dot_data__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in streamvis/v1/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateField = channel.unary_unary(
                '/streamvis.v1.Service/CreateField',
                request_serializer=streamvis_dot_v1_dot_data__pb2.CreateFieldRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.CreateFieldResponse.FromString,
                _registered_method=True)
        self.CreateSeries = channel.unary_unary(
                '/streamvis.v1.Service/CreateSeries',
                request_serializer=streamvis_dot_v1_dot_data__pb2.CreateSeriesRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.CreateSeriesResponse.FromString,
                _registered_method=True)
        self.AppendToSeries = channel.unary_unary(
                '/streamvis.v1.Service/AppendToSeries',
                request_serializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesResponse.FromString,
                _registered_method=True)
        self.CreateRun = channel.unary_unary(
                '/streamvis.v1.Service/CreateRun',
                request_serializer=streamvis_dot_v1_dot_data__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.CreateRunResponse.FromString,
                _registered_method=True)
        self.ReplaceRun = channel.unary_unary(
                '/streamvis.v1.Service/ReplaceRun',
                request_serializer=streamvis_dot_v1_dot_data__pb2.ReplaceRunRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.ReplaceRunResponse.FromString,
                _registered_method=True)
        self.DeleteRun = channel.unary_unary(
                '/streamvis.v1.Service/DeleteRun',
                request_serializer=streamvis_dot_v1_dot_data__pb2.DeleteRunRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.DeleteRunResponse.FromString,
                _registered_method=True)
        self.SetRunAttributes = channel.unary_unary(
                '/streamvis.v1.Service/SetRunAttributes',
                request_serializer=streamvis_dot_v1_dot_data__pb2.SetRunAttributesRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.SetRunAttributesResponse.FromString,
                _registered_method=True)
        self.DeleteEmptySeries = channel.unary_unary(
                '/streamvis.v1.Service/DeleteEmptySeries',
                request_serializer=streamvis_dot_v1_dot_data__pb2.DeleteEmptySeriesRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.DeleteEmptySeriesResponse.FromString,
                _registered_method=True)
        self.ListSeries = channel.unary_stream(
                '/streamvis.v1.Service/ListSeries',
                request_serializer=streamvis_dot_v1_dot_data__pb2.ListSeriesRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.Series.FromString,
                _registered_method=True)
        self.ListFields = channel.unary_stream(
                '/streamvis.v1.Service/ListFields',
                request_serializer=streamvis_dot_v1_dot_data__pb2.ListFieldsRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.Field.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_stream(
                '/streamvis.v1.Service/ListRuns',
                request_serializer=streamvis_dot_v1_dot_data__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=streamvis_dot_v1_dot_data__pb2.Run.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendToSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRunAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmptySeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """rpc ListFieldData (ListFieldDataRequest) returns (stream FieldDataResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateField': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateField,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.CreateFieldRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.CreateFieldResponse.SerializeToString,
            ),
            'CreateSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSeries,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.CreateSeriesRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.CreateSeriesResponse.SerializeToString,
            ),
            'AppendToSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendToSeries,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.AppendToSeriesResponse.SerializeToString,
            ),
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.CreateRunRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.CreateRunResponse.SerializeToString,
            ),
            'ReplaceRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceRun,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.ReplaceRunRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.ReplaceRunResponse.SerializeToString,
            ),
            'DeleteRun': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRun,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.DeleteRunRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.DeleteRunResponse.SerializeToString,
            ),
            'SetRunAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRunAttributes,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.SetRunAttributesRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.SetRunAttributesResponse.SerializeToString,
            ),
            'DeleteEmptySeries': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmptySeries,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.DeleteEmptySeriesRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.DeleteEmptySeriesResponse.SerializeToString,
            ),
            'ListSeries': grpc.unary_stream_rpc_method_handler(
                    servicer.ListSeries,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.ListSeriesRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.Series.SerializeToString,
            ),
            'ListFields': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFields,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.ListFieldsRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.Field.SerializeToString,
            ),
            'ListRuns': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=streamvis_dot_v1_dot_data__pb2.ListRunsRequest.FromString,
                    response_serializer=streamvis_dot_v1_dot_data__pb2.Run.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamvis.v1.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamvis.v1.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/CreateField',
            streamvis_dot_v1_dot_data__pb2.CreateFieldRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.CreateFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/CreateSeries',
            streamvis_dot_v1_dot_data__pb2.CreateSeriesRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.CreateSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendToSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/AppendToSeries',
            streamvis_dot_v1_dot_data__pb2.AppendToSeriesRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.AppendToSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/CreateRun',
            streamvis_dot_v1_dot_data__pb2.CreateRunRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.CreateRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/ReplaceRun',
            streamvis_dot_v1_dot_data__pb2.ReplaceRunRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.ReplaceRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/DeleteRun',
            streamvis_dot_v1_dot_data__pb2.DeleteRunRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.DeleteRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRunAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/SetRunAttributes',
            streamvis_dot_v1_dot_data__pb2.SetRunAttributesRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.SetRunAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEmptySeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamvis.v1.Service/DeleteEmptySeries',
            streamvis_dot_v1_dot_data__pb2.DeleteEmptySeriesRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.DeleteEmptySeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streamvis.v1.Service/ListSeries',
            streamvis_dot_v1_dot_data__pb2.ListSeriesRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.Series.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streamvis.v1.Service/ListFields',
            streamvis_dot_v1_dot_data__pb2.ListFieldsRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.Field.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streamvis.v1.Service/ListRuns',
            streamvis_dot_v1_dot_data__pb2.ListRunsRequest.SerializeToString,
            streamvis_dot_v1_dot_data__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
