_target_: streamvis.plot.PlotOpts

defaults:
  - _self_
  - filter@f1: filter 
  - filter@f2: filter 
  - filter@f3: filter
  - filter@f4: filter
  - filter@f5: filter
  - filter@c1: cfilter
  - filter@c2: cfilter
  - filter@c3: cfilter
  - filter@c4: cfilter
  - filter@c5: cfilter

fig_width: 9
fig_height: 6
dpi: 300
legend_at: 'upper right'

ty: scatter
series: null
x: null
y: null
cm: []
cs: []
g: []
o: []
s: []
l: []

tags: []
match_all: false

after: null
before: null


hydra:
  run:
    dir: ${oc.env:HOME}/.hydra
  output_subdir: .hydra

