lines:
  color:
    key_fun: ${oc.select:key_fun,"sni"}
    palette: ${oc.select:palette,"Turbo256"}
  figure_kwargs:
    title: 
      text: ${oc.select:title,"Title"}
    xaxis:
      axis_label: ${oc.select:xaxis_label,"X Axis"}
    yaxis:
      axis_label: ${oc.select:yaxis_label, "Y Axis"} 
  glyph_kind: line
  columns:
    - x
    - y

