# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streamvis/data.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streamvis/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14streamvis/data.proto\"/\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.FieldType\"\x1e\n\tFloatList\x12\x11\n\x05value\x18\x01 \x03(\x02\x42\x02\x10\x01\"\x1c\n\x07IntList\x12\x11\n\x05value\x18\x01 \x03(\x05\x42\x02\x10\x01\"H\n\x06Values\x12\x1c\n\x06\x66loats\x18\x02 \x01(\x0b\x32\n.FloatListH\x00\x12\x18\n\x04ints\x18\x03 \x01(\x0b\x32\x08.IntListH\x00\x42\x06\n\x04\x64\x61ta\"P\n\x08Metadata\x12\x0f\n\x07meta_id\x18\x01 \x01(\r\x12\r\n\x05scope\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x16\n\x06\x66ields\x18\x04 \x03(\x0b\x32\x06.Field\"R\n\x05\x45ntry\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\r\x12\x0f\n\x07meta_id\x18\x02 \x01(\r\x12\x12\n\nbeg_offset\x18\x03 \x01(\r\x12\x12\n\nend_offset\x18\x04 \x01(\r\"O\n\x04\x44\x61ta\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\x12\x15\n\x04\x61xes\x18\x03 \x03(\x0b\x32\x07.Values\x12\x0f\n\x07meta_id\x18\x04 \x01(\r\"?\n\x07\x43ontrol\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x07.Action\"H\n\x0cQueryRequest\x12\x12\n\x05scope\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_scopeB\x07\n\x05_name\"k\n\x0eStreamedRecord\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.RecordType\x12\x1d\n\x08metadata\x18\x02 \x01(\x0b\x32\t.MetadataH\x00\x12\x15\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x05.DataH\x00\x42\x08\n\x06record*\x1f\n\tFieldType\x12\t\n\x05\x46LOAT\x10\x00\x12\x07\n\x03INT\x10\x01*\x14\n\x06\x41\x63tion\x12\n\n\x06\x44\x45LETE\x10\x00*$\n\nRecordType\x12\x0c\n\x08METADATA\x10\x00\x12\x08\n\x04\x44\x41TA\x10\x01\x32\x41\n\rRecordService\x12\x30\n\x0cQueryRecords\x12\r.QueryRequest\x1a\x0f.StreamedRecord0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streamvis.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATLIST'].fields_by_name['value']._loaded_options = None
  _globals['_FLOATLIST'].fields_by_name['value']._serialized_options = b'\020\001'
  _globals['_INTLIST'].fields_by_name['value']._loaded_options = None
  _globals['_INTLIST'].fields_by_name['value']._serialized_options = b'\020\001'
  _globals['_FIELDTYPE']._serialized_start=704
  _globals['_FIELDTYPE']._serialized_end=735
  _globals['_ACTION']._serialized_start=737
  _globals['_ACTION']._serialized_end=757
  _globals['_RECORDTYPE']._serialized_start=759
  _globals['_RECORDTYPE']._serialized_end=795
  _globals['_FIELD']._serialized_start=24
  _globals['_FIELD']._serialized_end=71
  _globals['_FLOATLIST']._serialized_start=73
  _globals['_FLOATLIST']._serialized_end=103
  _globals['_INTLIST']._serialized_start=105
  _globals['_INTLIST']._serialized_end=133
  _globals['_VALUES']._serialized_start=135
  _globals['_VALUES']._serialized_end=207
  _globals['_METADATA']._serialized_start=209
  _globals['_METADATA']._serialized_end=289
  _globals['_ENTRY']._serialized_start=291
  _globals['_ENTRY']._serialized_end=373
  _globals['_DATA']._serialized_start=375
  _globals['_DATA']._serialized_end=454
  _globals['_CONTROL']._serialized_start=456
  _globals['_CONTROL']._serialized_end=519
  _globals['_QUERYREQUEST']._serialized_start=521
  _globals['_QUERYREQUEST']._serialized_end=593
  _globals['_STREAMEDRECORD']._serialized_start=595
  _globals['_STREAMEDRECORD']._serialized_end=702
  _globals['_RECORDSERVICE']._serialized_start=797
  _globals['_RECORDSERVICE']._serialized_end=862
# @@protoc_insertion_point(module_scope)
