// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: streamvis/v1/data.proto

package streamvis_v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "pier/pb/streamvis/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "streamvis.v1.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceCreateAttributeProcedure is the fully-qualified name of the Service's CreateAttribute RPC.
	ServiceCreateAttributeProcedure = "/streamvis.v1.Service/CreateAttribute"
	// ServiceCreateSeriesProcedure is the fully-qualified name of the Service's CreateSeries RPC.
	ServiceCreateSeriesProcedure = "/streamvis.v1.Service/CreateSeries"
	// ServiceAppendToSeriesProcedure is the fully-qualified name of the Service's AppendToSeries RPC.
	ServiceAppendToSeriesProcedure = "/streamvis.v1.Service/AppendToSeries"
	// ServiceCreateRunProcedure is the fully-qualified name of the Service's CreateRun RPC.
	ServiceCreateRunProcedure = "/streamvis.v1.Service/CreateRun"
	// ServiceDeleteRunProcedure is the fully-qualified name of the Service's DeleteRun RPC.
	ServiceDeleteRunProcedure = "/streamvis.v1.Service/DeleteRun"
	// ServiceListSeriesProcedure is the fully-qualified name of the Service's ListSeries RPC.
	ServiceListSeriesProcedure = "/streamvis.v1.Service/ListSeries"
	// ServiceListAttributesProcedure is the fully-qualified name of the Service's ListAttributes RPC.
	ServiceListAttributesProcedure = "/streamvis.v1.Service/ListAttributes"
)

// ServiceClient is a client for the streamvis.v1.Service service.
type ServiceClient interface {
	CreateAttribute(context.Context, *v1.CreateAttributeRequest) (*v1.CreateAttributeResponse, error)
	CreateSeries(context.Context, *v1.CreateSeriesRequest) (*v1.CreateSeriesResponse, error)
	AppendToSeries(context.Context, *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error)
	CreateRun(context.Context, *v1.CreateRunRequest) (*v1.CreateRunResponse, error)
	DeleteRun(context.Context, *v1.DeleteRunRequest) (*v1.DeleteRunResponse, error)
	ListSeries(context.Context, *v1.ListSeriesRequest) (*connect.ServerStreamForClient[v1.ListSeriesResponse], error)
	ListAttributes(context.Context, *v1.ListAttributesRequest) (*connect.ServerStreamForClient[v1.ListAttributesResponse], error)
}

// NewServiceClient constructs a client for the streamvis.v1.Service service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceMethods := v1.File_streamvis_v1_data_proto.Services().ByName("Service").Methods()
	return &serviceClient{
		createAttribute: connect.NewClient[v1.CreateAttributeRequest, v1.CreateAttributeResponse](
			httpClient,
			baseURL+ServiceCreateAttributeProcedure,
			connect.WithSchema(serviceMethods.ByName("CreateAttribute")),
			connect.WithClientOptions(opts...),
		),
		createSeries: connect.NewClient[v1.CreateSeriesRequest, v1.CreateSeriesResponse](
			httpClient,
			baseURL+ServiceCreateSeriesProcedure,
			connect.WithSchema(serviceMethods.ByName("CreateSeries")),
			connect.WithClientOptions(opts...),
		),
		appendToSeries: connect.NewClient[v1.AppendToSeriesRequest, v1.AppendToSeriesResponse](
			httpClient,
			baseURL+ServiceAppendToSeriesProcedure,
			connect.WithSchema(serviceMethods.ByName("AppendToSeries")),
			connect.WithClientOptions(opts...),
		),
		createRun: connect.NewClient[v1.CreateRunRequest, v1.CreateRunResponse](
			httpClient,
			baseURL+ServiceCreateRunProcedure,
			connect.WithSchema(serviceMethods.ByName("CreateRun")),
			connect.WithClientOptions(opts...),
		),
		deleteRun: connect.NewClient[v1.DeleteRunRequest, v1.DeleteRunResponse](
			httpClient,
			baseURL+ServiceDeleteRunProcedure,
			connect.WithSchema(serviceMethods.ByName("DeleteRun")),
			connect.WithClientOptions(opts...),
		),
		listSeries: connect.NewClient[v1.ListSeriesRequest, v1.ListSeriesResponse](
			httpClient,
			baseURL+ServiceListSeriesProcedure,
			connect.WithSchema(serviceMethods.ByName("ListSeries")),
			connect.WithClientOptions(opts...),
		),
		listAttributes: connect.NewClient[v1.ListAttributesRequest, v1.ListAttributesResponse](
			httpClient,
			baseURL+ServiceListAttributesProcedure,
			connect.WithSchema(serviceMethods.ByName("ListAttributes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	createAttribute *connect.Client[v1.CreateAttributeRequest, v1.CreateAttributeResponse]
	createSeries    *connect.Client[v1.CreateSeriesRequest, v1.CreateSeriesResponse]
	appendToSeries  *connect.Client[v1.AppendToSeriesRequest, v1.AppendToSeriesResponse]
	createRun       *connect.Client[v1.CreateRunRequest, v1.CreateRunResponse]
	deleteRun       *connect.Client[v1.DeleteRunRequest, v1.DeleteRunResponse]
	listSeries      *connect.Client[v1.ListSeriesRequest, v1.ListSeriesResponse]
	listAttributes  *connect.Client[v1.ListAttributesRequest, v1.ListAttributesResponse]
}

// CreateAttribute calls streamvis.v1.Service.CreateAttribute.
func (c *serviceClient) CreateAttribute(ctx context.Context, req *v1.CreateAttributeRequest) (*v1.CreateAttributeResponse, error) {
	response, err := c.createAttribute.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateSeries calls streamvis.v1.Service.CreateSeries.
func (c *serviceClient) CreateSeries(ctx context.Context, req *v1.CreateSeriesRequest) (*v1.CreateSeriesResponse, error) {
	response, err := c.createSeries.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AppendToSeries calls streamvis.v1.Service.AppendToSeries.
func (c *serviceClient) AppendToSeries(ctx context.Context, req *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error) {
	response, err := c.appendToSeries.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateRun calls streamvis.v1.Service.CreateRun.
func (c *serviceClient) CreateRun(ctx context.Context, req *v1.CreateRunRequest) (*v1.CreateRunResponse, error) {
	response, err := c.createRun.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteRun calls streamvis.v1.Service.DeleteRun.
func (c *serviceClient) DeleteRun(ctx context.Context, req *v1.DeleteRunRequest) (*v1.DeleteRunResponse, error) {
	response, err := c.deleteRun.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListSeries calls streamvis.v1.Service.ListSeries.
func (c *serviceClient) ListSeries(ctx context.Context, req *v1.ListSeriesRequest) (*connect.ServerStreamForClient[v1.ListSeriesResponse], error) {
	return c.listSeries.CallServerStream(ctx, connect.NewRequest(req))
}

// ListAttributes calls streamvis.v1.Service.ListAttributes.
func (c *serviceClient) ListAttributes(ctx context.Context, req *v1.ListAttributesRequest) (*connect.ServerStreamForClient[v1.ListAttributesResponse], error) {
	return c.listAttributes.CallServerStream(ctx, connect.NewRequest(req))
}

// ServiceHandler is an implementation of the streamvis.v1.Service service.
type ServiceHandler interface {
	CreateAttribute(context.Context, *v1.CreateAttributeRequest) (*v1.CreateAttributeResponse, error)
	CreateSeries(context.Context, *v1.CreateSeriesRequest) (*v1.CreateSeriesResponse, error)
	AppendToSeries(context.Context, *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error)
	CreateRun(context.Context, *v1.CreateRunRequest) (*v1.CreateRunResponse, error)
	DeleteRun(context.Context, *v1.DeleteRunRequest) (*v1.DeleteRunResponse, error)
	ListSeries(context.Context, *v1.ListSeriesRequest, *connect.ServerStream[v1.ListSeriesResponse]) error
	ListAttributes(context.Context, *v1.ListAttributesRequest, *connect.ServerStream[v1.ListAttributesResponse]) error
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceMethods := v1.File_streamvis_v1_data_proto.Services().ByName("Service").Methods()
	serviceCreateAttributeHandler := connect.NewUnaryHandlerSimple(
		ServiceCreateAttributeProcedure,
		svc.CreateAttribute,
		connect.WithSchema(serviceMethods.ByName("CreateAttribute")),
		connect.WithHandlerOptions(opts...),
	)
	serviceCreateSeriesHandler := connect.NewUnaryHandlerSimple(
		ServiceCreateSeriesProcedure,
		svc.CreateSeries,
		connect.WithSchema(serviceMethods.ByName("CreateSeries")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAppendToSeriesHandler := connect.NewUnaryHandlerSimple(
		ServiceAppendToSeriesProcedure,
		svc.AppendToSeries,
		connect.WithSchema(serviceMethods.ByName("AppendToSeries")),
		connect.WithHandlerOptions(opts...),
	)
	serviceCreateRunHandler := connect.NewUnaryHandlerSimple(
		ServiceCreateRunProcedure,
		svc.CreateRun,
		connect.WithSchema(serviceMethods.ByName("CreateRun")),
		connect.WithHandlerOptions(opts...),
	)
	serviceDeleteRunHandler := connect.NewUnaryHandlerSimple(
		ServiceDeleteRunProcedure,
		svc.DeleteRun,
		connect.WithSchema(serviceMethods.ByName("DeleteRun")),
		connect.WithHandlerOptions(opts...),
	)
	serviceListSeriesHandler := connect.NewServerStreamHandlerSimple(
		ServiceListSeriesProcedure,
		svc.ListSeries,
		connect.WithSchema(serviceMethods.ByName("ListSeries")),
		connect.WithHandlerOptions(opts...),
	)
	serviceListAttributesHandler := connect.NewServerStreamHandlerSimple(
		ServiceListAttributesProcedure,
		svc.ListAttributes,
		connect.WithSchema(serviceMethods.ByName("ListAttributes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/streamvis.v1.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceCreateAttributeProcedure:
			serviceCreateAttributeHandler.ServeHTTP(w, r)
		case ServiceCreateSeriesProcedure:
			serviceCreateSeriesHandler.ServeHTTP(w, r)
		case ServiceAppendToSeriesProcedure:
			serviceAppendToSeriesHandler.ServeHTTP(w, r)
		case ServiceCreateRunProcedure:
			serviceCreateRunHandler.ServeHTTP(w, r)
		case ServiceDeleteRunProcedure:
			serviceDeleteRunHandler.ServeHTTP(w, r)
		case ServiceListSeriesProcedure:
			serviceListSeriesHandler.ServeHTTP(w, r)
		case ServiceListAttributesProcedure:
			serviceListAttributesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) CreateAttribute(context.Context, *v1.CreateAttributeRequest) (*v1.CreateAttributeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.CreateAttribute is not implemented"))
}

func (UnimplementedServiceHandler) CreateSeries(context.Context, *v1.CreateSeriesRequest) (*v1.CreateSeriesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.CreateSeries is not implemented"))
}

func (UnimplementedServiceHandler) AppendToSeries(context.Context, *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.AppendToSeries is not implemented"))
}

func (UnimplementedServiceHandler) CreateRun(context.Context, *v1.CreateRunRequest) (*v1.CreateRunResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.CreateRun is not implemented"))
}

func (UnimplementedServiceHandler) DeleteRun(context.Context, *v1.DeleteRunRequest) (*v1.DeleteRunResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.DeleteRun is not implemented"))
}

func (UnimplementedServiceHandler) ListSeries(context.Context, *v1.ListSeriesRequest, *connect.ServerStream[v1.ListSeriesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.ListSeries is not implemented"))
}

func (UnimplementedServiceHandler) ListAttributes(context.Context, *v1.ListAttributesRequest, *connect.ServerStream[v1.ListAttributesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.ListAttributes is not implemented"))
}
