// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: streamvis/v1/data.proto

package streamvis_v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "pier/pb/streamvis/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "streamvis.v1.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceMakeOrGetScopeProcedure is the fully-qualified name of the Service's MakeOrGetScope RPC.
	ServiceMakeOrGetScopeProcedure = "/streamvis.v1.Service/MakeOrGetScope"
	// ServiceDeleteScopeProcedure is the fully-qualified name of the Service's DeleteScope RPC.
	ServiceDeleteScopeProcedure = "/streamvis.v1.Service/DeleteScope"
	// ServiceMakeOrGetSeriesProcedure is the fully-qualified name of the Service's MakeOrGetSeries RPC.
	ServiceMakeOrGetSeriesProcedure = "/streamvis.v1.Service/MakeOrGetSeries"
	// ServiceAppendToSeriesProcedure is the fully-qualified name of the Service's AppendToSeries RPC.
	ServiceAppendToSeriesProcedure = "/streamvis.v1.Service/AppendToSeries"
	// ServiceListScopesProcedure is the fully-qualified name of the Service's ListScopes RPC.
	ServiceListScopesProcedure = "/streamvis.v1.Service/ListScopes"
)

// ServiceClient is a client for the streamvis.v1.Service service.
type ServiceClient interface {
	MakeOrGetScope(context.Context, *v1.GetScopeRequest) (*v1.GetScopeResponse, error)
	DeleteScope(context.Context, *v1.DeleteScopeRequest) (*v1.DeleteScopeResponse, error)
	MakeOrGetSeries(context.Context, *v1.GetSeriesRequest) (*v1.GetSeriesResponse, error)
	AppendToSeries(context.Context, *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error)
	ListScopes(context.Context, *v1.ListScopesRequest) (*connect.ServerStreamForClient[v1.ListScopesResponse], error)
}

// NewServiceClient constructs a client for the streamvis.v1.Service service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceMethods := v1.File_streamvis_v1_data_proto.Services().ByName("Service").Methods()
	return &serviceClient{
		makeOrGetScope: connect.NewClient[v1.GetScopeRequest, v1.GetScopeResponse](
			httpClient,
			baseURL+ServiceMakeOrGetScopeProcedure,
			connect.WithSchema(serviceMethods.ByName("MakeOrGetScope")),
			connect.WithClientOptions(opts...),
		),
		deleteScope: connect.NewClient[v1.DeleteScopeRequest, v1.DeleteScopeResponse](
			httpClient,
			baseURL+ServiceDeleteScopeProcedure,
			connect.WithSchema(serviceMethods.ByName("DeleteScope")),
			connect.WithClientOptions(opts...),
		),
		makeOrGetSeries: connect.NewClient[v1.GetSeriesRequest, v1.GetSeriesResponse](
			httpClient,
			baseURL+ServiceMakeOrGetSeriesProcedure,
			connect.WithSchema(serviceMethods.ByName("MakeOrGetSeries")),
			connect.WithClientOptions(opts...),
		),
		appendToSeries: connect.NewClient[v1.AppendToSeriesRequest, v1.AppendToSeriesResponse](
			httpClient,
			baseURL+ServiceAppendToSeriesProcedure,
			connect.WithSchema(serviceMethods.ByName("AppendToSeries")),
			connect.WithClientOptions(opts...),
		),
		listScopes: connect.NewClient[v1.ListScopesRequest, v1.ListScopesResponse](
			httpClient,
			baseURL+ServiceListScopesProcedure,
			connect.WithSchema(serviceMethods.ByName("ListScopes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	makeOrGetScope  *connect.Client[v1.GetScopeRequest, v1.GetScopeResponse]
	deleteScope     *connect.Client[v1.DeleteScopeRequest, v1.DeleteScopeResponse]
	makeOrGetSeries *connect.Client[v1.GetSeriesRequest, v1.GetSeriesResponse]
	appendToSeries  *connect.Client[v1.AppendToSeriesRequest, v1.AppendToSeriesResponse]
	listScopes      *connect.Client[v1.ListScopesRequest, v1.ListScopesResponse]
}

// MakeOrGetScope calls streamvis.v1.Service.MakeOrGetScope.
func (c *serviceClient) MakeOrGetScope(ctx context.Context, req *v1.GetScopeRequest) (*v1.GetScopeResponse, error) {
	response, err := c.makeOrGetScope.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteScope calls streamvis.v1.Service.DeleteScope.
func (c *serviceClient) DeleteScope(ctx context.Context, req *v1.DeleteScopeRequest) (*v1.DeleteScopeResponse, error) {
	response, err := c.deleteScope.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// MakeOrGetSeries calls streamvis.v1.Service.MakeOrGetSeries.
func (c *serviceClient) MakeOrGetSeries(ctx context.Context, req *v1.GetSeriesRequest) (*v1.GetSeriesResponse, error) {
	response, err := c.makeOrGetSeries.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AppendToSeries calls streamvis.v1.Service.AppendToSeries.
func (c *serviceClient) AppendToSeries(ctx context.Context, req *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error) {
	response, err := c.appendToSeries.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListScopes calls streamvis.v1.Service.ListScopes.
func (c *serviceClient) ListScopes(ctx context.Context, req *v1.ListScopesRequest) (*connect.ServerStreamForClient[v1.ListScopesResponse], error) {
	return c.listScopes.CallServerStream(ctx, connect.NewRequest(req))
}

// ServiceHandler is an implementation of the streamvis.v1.Service service.
type ServiceHandler interface {
	MakeOrGetScope(context.Context, *v1.GetScopeRequest) (*v1.GetScopeResponse, error)
	DeleteScope(context.Context, *v1.DeleteScopeRequest) (*v1.DeleteScopeResponse, error)
	MakeOrGetSeries(context.Context, *v1.GetSeriesRequest) (*v1.GetSeriesResponse, error)
	AppendToSeries(context.Context, *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error)
	ListScopes(context.Context, *v1.ListScopesRequest, *connect.ServerStream[v1.ListScopesResponse]) error
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceMethods := v1.File_streamvis_v1_data_proto.Services().ByName("Service").Methods()
	serviceMakeOrGetScopeHandler := connect.NewUnaryHandlerSimple(
		ServiceMakeOrGetScopeProcedure,
		svc.MakeOrGetScope,
		connect.WithSchema(serviceMethods.ByName("MakeOrGetScope")),
		connect.WithHandlerOptions(opts...),
	)
	serviceDeleteScopeHandler := connect.NewUnaryHandlerSimple(
		ServiceDeleteScopeProcedure,
		svc.DeleteScope,
		connect.WithSchema(serviceMethods.ByName("DeleteScope")),
		connect.WithHandlerOptions(opts...),
	)
	serviceMakeOrGetSeriesHandler := connect.NewUnaryHandlerSimple(
		ServiceMakeOrGetSeriesProcedure,
		svc.MakeOrGetSeries,
		connect.WithSchema(serviceMethods.ByName("MakeOrGetSeries")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAppendToSeriesHandler := connect.NewUnaryHandlerSimple(
		ServiceAppendToSeriesProcedure,
		svc.AppendToSeries,
		connect.WithSchema(serviceMethods.ByName("AppendToSeries")),
		connect.WithHandlerOptions(opts...),
	)
	serviceListScopesHandler := connect.NewServerStreamHandlerSimple(
		ServiceListScopesProcedure,
		svc.ListScopes,
		connect.WithSchema(serviceMethods.ByName("ListScopes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/streamvis.v1.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceMakeOrGetScopeProcedure:
			serviceMakeOrGetScopeHandler.ServeHTTP(w, r)
		case ServiceDeleteScopeProcedure:
			serviceDeleteScopeHandler.ServeHTTP(w, r)
		case ServiceMakeOrGetSeriesProcedure:
			serviceMakeOrGetSeriesHandler.ServeHTTP(w, r)
		case ServiceAppendToSeriesProcedure:
			serviceAppendToSeriesHandler.ServeHTTP(w, r)
		case ServiceListScopesProcedure:
			serviceListScopesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) MakeOrGetScope(context.Context, *v1.GetScopeRequest) (*v1.GetScopeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.MakeOrGetScope is not implemented"))
}

func (UnimplementedServiceHandler) DeleteScope(context.Context, *v1.DeleteScopeRequest) (*v1.DeleteScopeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.DeleteScope is not implemented"))
}

func (UnimplementedServiceHandler) MakeOrGetSeries(context.Context, *v1.GetSeriesRequest) (*v1.GetSeriesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.MakeOrGetSeries is not implemented"))
}

func (UnimplementedServiceHandler) AppendToSeries(context.Context, *v1.AppendToSeriesRequest) (*v1.AppendToSeriesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.AppendToSeries is not implemented"))
}

func (UnimplementedServiceHandler) ListScopes(context.Context, *v1.ListScopesRequest, *connect.ServerStream[v1.ListScopesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("streamvis.v1.Service.ListScopes is not implemented"))
}
