DROP TABLE IF EXISTS data_lock;
DROP TABLE IF EXISTS coord_data;
DROP TABLE IF EXISTS chunk;
DROP TABLE IF EXISTS run_attr;
DROP TABLE IF EXISTS coord;
DROP TABLE IF EXISTS run;
DROP TABLE IF EXISTS field;
DROP TABLE IF EXISTS series;

