DROP TABLE IF EXISTS field_data;
DROP TABLE IF EXISTS field;
DROP TABLE IF EXISTS chunk;
DROP TABLE IF EXISTS run_attr;
DROP TABLE IF EXISTS run;
DROP TABLE IF EXISTS attr;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS data_lock;
DROP FUNCTION IF EXISTS valid_enc_typ;
DROP FUNCTION IF EXISTS get_enc_signature;

