// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: streamvis/v1/data.proto

package streamvis_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesName    string                 `protobuf:"bytes,1,opt,name=series_name,json=seriesName,proto3" json:"series_name,omitempty"`
	Structure     map[string]string      `protobuf:"bytes,2,rep,name=structure,proto3" json:"structure,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesRequest) Reset() {
	*x = GetSeriesRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesRequest) ProtoMessage() {}

func (x *GetSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeriesRequest) GetSeriesName() string {
	if x != nil {
		return x.SeriesName
	}
	return ""
}

func (x *GetSeriesRequest) GetStructure() map[string]string {
	if x != nil {
		return x.Structure
	}
	return nil
}

type GetSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesHandle  string                 `protobuf:"bytes,1,opt,name=series_handle,json=seriesHandle,proto3" json:"series_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesResponse) Reset() {
	*x = GetSeriesResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesResponse) ProtoMessage() {}

func (x *GetSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetSeriesResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeriesResponse) GetSeriesHandle() string {
	if x != nil {
		return x.SeriesHandle
	}
	return ""
}

type EncTyp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  []byte                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Shape []uint32               `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	// Types that are valid to be assigned to Spans:
	//
	//	*EncTyp_Ival
	//	*EncTyp_Fval
	Spans         isEncTyp_Spans `protobuf_oneof:"spans"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncTyp) Reset() {
	*x = EncTyp{}
	mi := &file_streamvis_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncTyp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncTyp) ProtoMessage() {}

func (x *EncTyp) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncTyp.ProtoReflect.Descriptor instead.
func (*EncTyp) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *EncTyp) GetBase() []byte {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EncTyp) GetShape() []uint32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *EncTyp) GetSpans() isEncTyp_Spans {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *EncTyp) GetIval() *IntValues {
	if x != nil {
		if x, ok := x.Spans.(*EncTyp_Ival); ok {
			return x.Ival
		}
	}
	return nil
}

func (x *EncTyp) GetFval() *FloatValues {
	if x != nil {
		if x, ok := x.Spans.(*EncTyp_Fval); ok {
			return x.Fval
		}
	}
	return nil
}

type isEncTyp_Spans interface {
	isEncTyp_Spans()
}

type EncTyp_Ival struct {
	Ival *IntValues `protobuf:"bytes,3,opt,name=ival,proto3,oneof"`
}

type EncTyp_Fval struct {
	Fval *FloatValues `protobuf:"bytes,4,opt,name=fval,proto3,oneof"`
}

func (*EncTyp_Ival) isEncTyp_Spans() {}

func (*EncTyp_Fval) isEncTyp_Spans() {}

type IntValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*OptionalInt         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntValues) Reset() {
	*x = IntValues{}
	mi := &file_streamvis_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntValues) ProtoMessage() {}

func (x *IntValues) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntValues.ProtoReflect.Descriptor instead.
func (*IntValues) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *IntValues) GetValues() []*OptionalInt {
	if x != nil {
		return x.Values
	}
	return nil
}

type OptionalInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalInt) Reset() {
	*x = OptionalInt{}
	mi := &file_streamvis_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalInt) ProtoMessage() {}

func (x *OptionalInt) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalInt.ProtoReflect.Descriptor instead.
func (*OptionalInt) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *OptionalInt) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type FloatValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*OptionalFloat       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatValues) Reset() {
	*x = FloatValues{}
	mi := &file_streamvis_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatValues) ProtoMessage() {}

func (x *FloatValues) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatValues.ProtoReflect.Descriptor instead.
func (*FloatValues) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *FloatValues) GetValues() []*OptionalFloat {
	if x != nil {
		return x.Values
	}
	return nil
}

type OptionalFloat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float32               `protobuf:"fixed32,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalFloat) Reset() {
	*x = OptionalFloat{}
	mi := &file_streamvis_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalFloat) ProtoMessage() {}

func (x *OptionalFloat) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalFloat.ProtoReflect.Descriptor instead.
func (*OptionalFloat) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{6}
}

func (x *OptionalFloat) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type AppendToSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesHandle  string                 `protobuf:"bytes,1,opt,name=series_handle,json=seriesHandle,proto3" json:"series_handle,omitempty"`
	RunHandle     string                 `protobuf:"bytes,2,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"`
	FieldNames    []string               `protobuf:"bytes,3,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"`
	FieldVals     []*EncTyp              `protobuf:"bytes,4,rep,name=field_vals,json=fieldVals,proto3" json:"field_vals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToSeriesRequest) Reset() {
	*x = AppendToSeriesRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToSeriesRequest) ProtoMessage() {}

func (x *AppendToSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToSeriesRequest.ProtoReflect.Descriptor instead.
func (*AppendToSeriesRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{7}
}

func (x *AppendToSeriesRequest) GetSeriesHandle() string {
	if x != nil {
		return x.SeriesHandle
	}
	return ""
}

func (x *AppendToSeriesRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

func (x *AppendToSeriesRequest) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

func (x *AppendToSeriesRequest) GetFieldVals() []*EncTyp {
	if x != nil {
		return x.FieldVals
	}
	return nil
}

type AppendToSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToSeriesResponse) Reset() {
	*x = AppendToSeriesResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToSeriesResponse) ProtoMessage() {}

func (x *AppendToSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToSeriesResponse.ProtoReflect.Descriptor instead.
func (*AppendToSeriesResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{8}
}

func (x *AppendToSeriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{9}
}

type CreateRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunHandle     string                 `protobuf:"bytes,1,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunResponse) Reset() {
	*x = CreateRunResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunResponse) ProtoMessage() {}

func (x *CreateRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunResponse.ProtoReflect.Descriptor instead.
func (*CreateRunResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRunResponse) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

type DeleteRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunHandle     string                 `protobuf:"bytes,1,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunRequest) Reset() {
	*x = DeleteRunRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunRequest) ProtoMessage() {}

func (x *DeleteRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRunRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

type DeleteRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunResponse) Reset() {
	*x = DeleteRunResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunResponse) ProtoMessage() {}

func (x *DeleteRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunResponse.ProtoReflect.Descriptor instead.
func (*DeleteRunResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_streamvis_v1_data_proto protoreflect.FileDescriptor

const file_streamvis_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x17streamvis/v1/data.proto\x12\fstreamvis.v1\"\xbe\x01\n" +
	"\x10GetSeriesRequest\x12\x1f\n" +
	"\vseries_name\x18\x01 \x01(\tR\n" +
	"seriesName\x12K\n" +
	"\tstructure\x18\x02 \x03(\v2-.streamvis.v1.GetSeriesRequest.StructureEntryR\tstructure\x1a<\n" +
	"\x0eStructureEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x11GetSeriesResponse\x12#\n" +
	"\rseries_handle\x18\x01 \x01(\tR\fseriesHandle\"\x9b\x01\n" +
	"\x06EncTyp\x12\x12\n" +
	"\x04base\x18\x01 \x01(\fR\x04base\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\rR\x05shape\x12-\n" +
	"\x04ival\x18\x03 \x01(\v2\x17.streamvis.v1.IntValuesH\x00R\x04ival\x12/\n" +
	"\x04fval\x18\x04 \x01(\v2\x19.streamvis.v1.FloatValuesH\x00R\x04fvalB\a\n" +
	"\x05spans\">\n" +
	"\tIntValues\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.streamvis.v1.OptionalIntR\x06values\"2\n" +
	"\vOptionalInt\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x05H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"B\n" +
	"\vFloatValues\x123\n" +
	"\x06values\x18\x01 \x03(\v2\x1b.streamvis.v1.OptionalFloatR\x06values\"4\n" +
	"\rOptionalFloat\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x02H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xb1\x01\n" +
	"\x15AppendToSeriesRequest\x12#\n" +
	"\rseries_handle\x18\x01 \x01(\tR\fseriesHandle\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x02 \x01(\tR\trunHandle\x12\x1f\n" +
	"\vfield_names\x18\x03 \x03(\tR\n" +
	"fieldNames\x123\n" +
	"\n" +
	"field_vals\x18\x04 \x03(\v2\x14.streamvis.v1.EncTypR\tfieldVals\"2\n" +
	"\x16AppendToSeriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10CreateRunRequest\"2\n" +
	"\x11CreateRunResponse\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x01 \x01(\tR\trunHandle\"1\n" +
	"\x10DeleteRunRequest\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x01 \x01(\tR\trunHandle\"-\n" +
	"\x11DeleteRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd6\x02\n" +
	"\aService\x12R\n" +
	"\x0fMakeOrGetSeries\x12\x1e.streamvis.v1.GetSeriesRequest\x1a\x1f.streamvis.v1.GetSeriesResponse\x12[\n" +
	"\x0eAppendToSeries\x12#.streamvis.v1.AppendToSeriesRequest\x1a$.streamvis.v1.AppendToSeriesResponse\x12L\n" +
	"\tCreateRun\x12\x1e.streamvis.v1.CreateRunRequest\x1a\x1f.streamvis.v1.CreateRunResponse\x12L\n" +
	"\tDeleteRun\x12\x1e.streamvis.v1.DeleteRunRequest\x1a\x1f.streamvis.v1.DeleteRunResponseB#Z!pier/pb/streamvis/v1;streamvis_v1b\x06proto3"

var (
	file_streamvis_v1_data_proto_rawDescOnce sync.Once
	file_streamvis_v1_data_proto_rawDescData []byte
)

func file_streamvis_v1_data_proto_rawDescGZIP() []byte {
	file_streamvis_v1_data_proto_rawDescOnce.Do(func() {
		file_streamvis_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamvis_v1_data_proto_rawDesc), len(file_streamvis_v1_data_proto_rawDesc)))
	})
	return file_streamvis_v1_data_proto_rawDescData
}

var file_streamvis_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_streamvis_v1_data_proto_goTypes = []any{
	(*GetSeriesRequest)(nil),       // 0: streamvis.v1.GetSeriesRequest
	(*GetSeriesResponse)(nil),      // 1: streamvis.v1.GetSeriesResponse
	(*EncTyp)(nil),                 // 2: streamvis.v1.EncTyp
	(*IntValues)(nil),              // 3: streamvis.v1.IntValues
	(*OptionalInt)(nil),            // 4: streamvis.v1.OptionalInt
	(*FloatValues)(nil),            // 5: streamvis.v1.FloatValues
	(*OptionalFloat)(nil),          // 6: streamvis.v1.OptionalFloat
	(*AppendToSeriesRequest)(nil),  // 7: streamvis.v1.AppendToSeriesRequest
	(*AppendToSeriesResponse)(nil), // 8: streamvis.v1.AppendToSeriesResponse
	(*CreateRunRequest)(nil),       // 9: streamvis.v1.CreateRunRequest
	(*CreateRunResponse)(nil),      // 10: streamvis.v1.CreateRunResponse
	(*DeleteRunRequest)(nil),       // 11: streamvis.v1.DeleteRunRequest
	(*DeleteRunResponse)(nil),      // 12: streamvis.v1.DeleteRunResponse
	nil,                            // 13: streamvis.v1.GetSeriesRequest.StructureEntry
}
var file_streamvis_v1_data_proto_depIdxs = []int32{
	13, // 0: streamvis.v1.GetSeriesRequest.structure:type_name -> streamvis.v1.GetSeriesRequest.StructureEntry
	3,  // 1: streamvis.v1.EncTyp.ival:type_name -> streamvis.v1.IntValues
	5,  // 2: streamvis.v1.EncTyp.fval:type_name -> streamvis.v1.FloatValues
	4,  // 3: streamvis.v1.IntValues.values:type_name -> streamvis.v1.OptionalInt
	6,  // 4: streamvis.v1.FloatValues.values:type_name -> streamvis.v1.OptionalFloat
	2,  // 5: streamvis.v1.AppendToSeriesRequest.field_vals:type_name -> streamvis.v1.EncTyp
	0,  // 6: streamvis.v1.Service.MakeOrGetSeries:input_type -> streamvis.v1.GetSeriesRequest
	7,  // 7: streamvis.v1.Service.AppendToSeries:input_type -> streamvis.v1.AppendToSeriesRequest
	9,  // 8: streamvis.v1.Service.CreateRun:input_type -> streamvis.v1.CreateRunRequest
	11, // 9: streamvis.v1.Service.DeleteRun:input_type -> streamvis.v1.DeleteRunRequest
	1,  // 10: streamvis.v1.Service.MakeOrGetSeries:output_type -> streamvis.v1.GetSeriesResponse
	8,  // 11: streamvis.v1.Service.AppendToSeries:output_type -> streamvis.v1.AppendToSeriesResponse
	10, // 12: streamvis.v1.Service.CreateRun:output_type -> streamvis.v1.CreateRunResponse
	12, // 13: streamvis.v1.Service.DeleteRun:output_type -> streamvis.v1.DeleteRunResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_streamvis_v1_data_proto_init() }
func file_streamvis_v1_data_proto_init() {
	if File_streamvis_v1_data_proto != nil {
		return
	}
	file_streamvis_v1_data_proto_msgTypes[2].OneofWrappers = []any{
		(*EncTyp_Ival)(nil),
		(*EncTyp_Fval)(nil),
	}
	file_streamvis_v1_data_proto_msgTypes[4].OneofWrappers = []any{}
	file_streamvis_v1_data_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamvis_v1_data_proto_rawDesc), len(file_streamvis_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamvis_v1_data_proto_goTypes,
		DependencyIndexes: file_streamvis_v1_data_proto_depIdxs,
		MessageInfos:      file_streamvis_v1_data_proto_msgTypes,
	}.Build()
	File_streamvis_v1_data_proto = out.File
	file_streamvis_v1_data_proto_goTypes = nil
	file_streamvis_v1_data_proto_depIdxs = nil
}
