// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: streamvis/v1/data.proto

package streamvis_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScopeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScopeName      string                 `protobuf:"bytes,1,opt,name=scope_name,json=scopeName,proto3" json:"scope_name,omitempty"`
	DeleteExisting bool                   `protobuf:"varint,2,opt,name=delete_existing,json=deleteExisting,proto3" json:"delete_existing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetScopeRequest) Reset() {
	*x = GetScopeRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScopeRequest) ProtoMessage() {}

func (x *GetScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScopeRequest.ProtoReflect.Descriptor instead.
func (*GetScopeRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetScopeRequest) GetScopeName() string {
	if x != nil {
		return x.ScopeName
	}
	return ""
}

func (x *GetScopeRequest) GetDeleteExisting() bool {
	if x != nil {
		return x.DeleteExisting
	}
	return false
}

type GetScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopeHandle   string                 `protobuf:"bytes,1,opt,name=scope_handle,json=scopeHandle,proto3" json:"scope_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScopeResponse) Reset() {
	*x = GetScopeResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScopeResponse) ProtoMessage() {}

func (x *GetScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScopeResponse.ProtoReflect.Descriptor instead.
func (*GetScopeResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetScopeResponse) GetScopeHandle() string {
	if x != nil {
		return x.ScopeHandle
	}
	return ""
}

type DeleteScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopeHandle   string                 `protobuf:"bytes,1,opt,name=scope_handle,json=scopeHandle,proto3" json:"scope_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScopeRequest) Reset() {
	*x = DeleteScopeRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScopeRequest) ProtoMessage() {}

func (x *DeleteScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScopeRequest.ProtoReflect.Descriptor instead.
func (*DeleteScopeRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteScopeRequest) GetScopeHandle() string {
	if x != nil {
		return x.ScopeHandle
	}
	return ""
}

type DeleteScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScopeResponse) Reset() {
	*x = DeleteScopeResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScopeResponse) ProtoMessage() {}

func (x *DeleteScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScopeResponse.ProtoReflect.Descriptor instead.
func (*DeleteScopeResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteScopeResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetSeriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScopeHandle    string                 `protobuf:"bytes,1,opt,name=scope_handle,json=scopeHandle,proto3" json:"scope_handle,omitempty"`
	SeriesName     string                 `protobuf:"bytes,2,opt,name=series_name,json=seriesName,proto3" json:"series_name,omitempty"`
	Structure      map[string]string      `protobuf:"bytes,3,rep,name=structure,proto3" json:"structure,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeleteExisting bool                   `protobuf:"varint,4,opt,name=delete_existing,json=deleteExisting,proto3" json:"delete_existing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSeriesRequest) Reset() {
	*x = GetSeriesRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesRequest) ProtoMessage() {}

func (x *GetSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeriesRequest) GetScopeHandle() string {
	if x != nil {
		return x.ScopeHandle
	}
	return ""
}

func (x *GetSeriesRequest) GetSeriesName() string {
	if x != nil {
		return x.SeriesName
	}
	return ""
}

func (x *GetSeriesRequest) GetStructure() map[string]string {
	if x != nil {
		return x.Structure
	}
	return nil
}

func (x *GetSeriesRequest) GetDeleteExisting() bool {
	if x != nil {
		return x.DeleteExisting
	}
	return false
}

type GetSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesHandle  string                 `protobuf:"bytes,1,opt,name=series_handle,json=seriesHandle,proto3" json:"series_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesResponse) Reset() {
	*x = GetSeriesResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesResponse) ProtoMessage() {}

func (x *GetSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetSeriesResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *GetSeriesResponse) GetSeriesHandle() string {
	if x != nil {
		return x.SeriesHandle
	}
	return ""
}

type EncTyp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  []byte                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Shape []uint32               `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	// Types that are valid to be assigned to Spans:
	//
	//	*EncTyp_Ival
	//	*EncTyp_Fval
	Spans         isEncTyp_Spans `protobuf_oneof:"spans"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncTyp) Reset() {
	*x = EncTyp{}
	mi := &file_streamvis_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncTyp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncTyp) ProtoMessage() {}

func (x *EncTyp) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncTyp.ProtoReflect.Descriptor instead.
func (*EncTyp) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{6}
}

func (x *EncTyp) GetBase() []byte {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EncTyp) GetShape() []uint32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *EncTyp) GetSpans() isEncTyp_Spans {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *EncTyp) GetIval() *IntValues {
	if x != nil {
		if x, ok := x.Spans.(*EncTyp_Ival); ok {
			return x.Ival
		}
	}
	return nil
}

func (x *EncTyp) GetFval() *FloatValues {
	if x != nil {
		if x, ok := x.Spans.(*EncTyp_Fval); ok {
			return x.Fval
		}
	}
	return nil
}

type isEncTyp_Spans interface {
	isEncTyp_Spans()
}

type EncTyp_Ival struct {
	Ival *IntValues `protobuf:"bytes,3,opt,name=ival,proto3,oneof"`
}

type EncTyp_Fval struct {
	Fval *FloatValues `protobuf:"bytes,4,opt,name=fval,proto3,oneof"`
}

func (*EncTyp_Ival) isEncTyp_Spans() {}

func (*EncTyp_Fval) isEncTyp_Spans() {}

type IntValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []uint32               `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntValues) Reset() {
	*x = IntValues{}
	mi := &file_streamvis_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntValues) ProtoMessage() {}

func (x *IntValues) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntValues.ProtoReflect.Descriptor instead.
func (*IntValues) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{7}
}

func (x *IntValues) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type FloatValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatValues) Reset() {
	*x = FloatValues{}
	mi := &file_streamvis_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatValues) ProtoMessage() {}

func (x *FloatValues) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatValues.ProtoReflect.Descriptor instead.
func (*FloatValues) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{8}
}

func (x *FloatValues) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type AppendToSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesHandle  string                 `protobuf:"bytes,1,opt,name=series_handle,json=seriesHandle,proto3" json:"series_handle,omitempty"`
	FieldNames    []string               `protobuf:"bytes,2,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"`
	FieldVals     []*EncTyp              `protobuf:"bytes,3,rep,name=field_vals,json=fieldVals,proto3" json:"field_vals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToSeriesRequest) Reset() {
	*x = AppendToSeriesRequest{}
	mi := &file_streamvis_v1_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToSeriesRequest) ProtoMessage() {}

func (x *AppendToSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToSeriesRequest.ProtoReflect.Descriptor instead.
func (*AppendToSeriesRequest) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{9}
}

func (x *AppendToSeriesRequest) GetSeriesHandle() string {
	if x != nil {
		return x.SeriesHandle
	}
	return ""
}

func (x *AppendToSeriesRequest) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

func (x *AppendToSeriesRequest) GetFieldVals() []*EncTyp {
	if x != nil {
		return x.FieldVals
	}
	return nil
}

type AppendToSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToSeriesResponse) Reset() {
	*x = AppendToSeriesResponse{}
	mi := &file_streamvis_v1_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToSeriesResponse) ProtoMessage() {}

func (x *AppendToSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamvis_v1_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToSeriesResponse.ProtoReflect.Descriptor instead.
func (*AppendToSeriesResponse) Descriptor() ([]byte, []int) {
	return file_streamvis_v1_data_proto_rawDescGZIP(), []int{10}
}

func (x *AppendToSeriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_streamvis_v1_data_proto protoreflect.FileDescriptor

const file_streamvis_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x17streamvis/v1/data.proto\x12\fstreamvis.v1\"Y\n" +
	"\x0fGetScopeRequest\x12\x1d\n" +
	"\n" +
	"scope_name\x18\x01 \x01(\tR\tscopeName\x12'\n" +
	"\x0fdelete_existing\x18\x02 \x01(\bR\x0edeleteExisting\"5\n" +
	"\x10GetScopeResponse\x12!\n" +
	"\fscope_handle\x18\x01 \x01(\tR\vscopeHandle\"7\n" +
	"\x12DeleteScopeRequest\x12!\n" +
	"\fscope_handle\x18\x01 \x01(\tR\vscopeHandle\"/\n" +
	"\x13DeleteScopeResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x8a\x02\n" +
	"\x10GetSeriesRequest\x12!\n" +
	"\fscope_handle\x18\x01 \x01(\tR\vscopeHandle\x12\x1f\n" +
	"\vseries_name\x18\x02 \x01(\tR\n" +
	"seriesName\x12K\n" +
	"\tstructure\x18\x03 \x03(\v2-.streamvis.v1.GetSeriesRequest.StructureEntryR\tstructure\x12'\n" +
	"\x0fdelete_existing\x18\x04 \x01(\bR\x0edeleteExisting\x1a<\n" +
	"\x0eStructureEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x11GetSeriesResponse\x12#\n" +
	"\rseries_handle\x18\x01 \x01(\tR\fseriesHandle\"\x9b\x01\n" +
	"\x06EncTyp\x12\x12\n" +
	"\x04base\x18\x01 \x01(\fR\x04base\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\rR\x05shape\x12-\n" +
	"\x04ival\x18\x03 \x01(\v2\x17.streamvis.v1.IntValuesH\x00R\x04ival\x12/\n" +
	"\x04fval\x18\x04 \x01(\v2\x19.streamvis.v1.FloatValuesH\x00R\x04fvalB\a\n" +
	"\x05spans\"#\n" +
	"\tIntValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\rR\x06values\"%\n" +
	"\vFloatValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\x92\x01\n" +
	"\x15AppendToSeriesRequest\x12#\n" +
	"\rseries_handle\x18\x01 \x01(\tR\fseriesHandle\x12\x1f\n" +
	"\vfield_names\x18\x02 \x03(\tR\n" +
	"fieldNames\x123\n" +
	"\n" +
	"field_vals\x18\x03 \x03(\v2\x14.streamvis.v1.EncTypR\tfieldVals\"2\n" +
	"\x16AppendToSeriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xdf\x02\n" +
	"\aService\x12O\n" +
	"\x0eMakeOrGetScope\x12\x1d.streamvis.v1.GetScopeRequest\x1a\x1e.streamvis.v1.GetScopeResponse\x12R\n" +
	"\vDeleteScope\x12 .streamvis.v1.DeleteScopeRequest\x1a!.streamvis.v1.DeleteScopeResponse\x12R\n" +
	"\x0fMakeOrGetSeries\x12\x1e.streamvis.v1.GetSeriesRequest\x1a\x1f.streamvis.v1.GetSeriesResponse\x12[\n" +
	"\x0eAppendToSeries\x12#.streamvis.v1.AppendToSeriesRequest\x1a$.streamvis.v1.AppendToSeriesResponseB#Z!pier/pb/streamvis/v1;streamvis_v1b\x06proto3"

var (
	file_streamvis_v1_data_proto_rawDescOnce sync.Once
	file_streamvis_v1_data_proto_rawDescData []byte
)

func file_streamvis_v1_data_proto_rawDescGZIP() []byte {
	file_streamvis_v1_data_proto_rawDescOnce.Do(func() {
		file_streamvis_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamvis_v1_data_proto_rawDesc), len(file_streamvis_v1_data_proto_rawDesc)))
	})
	return file_streamvis_v1_data_proto_rawDescData
}

var file_streamvis_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_streamvis_v1_data_proto_goTypes = []any{
	(*GetScopeRequest)(nil),        // 0: streamvis.v1.GetScopeRequest
	(*GetScopeResponse)(nil),       // 1: streamvis.v1.GetScopeResponse
	(*DeleteScopeRequest)(nil),     // 2: streamvis.v1.DeleteScopeRequest
	(*DeleteScopeResponse)(nil),    // 3: streamvis.v1.DeleteScopeResponse
	(*GetSeriesRequest)(nil),       // 4: streamvis.v1.GetSeriesRequest
	(*GetSeriesResponse)(nil),      // 5: streamvis.v1.GetSeriesResponse
	(*EncTyp)(nil),                 // 6: streamvis.v1.EncTyp
	(*IntValues)(nil),              // 7: streamvis.v1.IntValues
	(*FloatValues)(nil),            // 8: streamvis.v1.FloatValues
	(*AppendToSeriesRequest)(nil),  // 9: streamvis.v1.AppendToSeriesRequest
	(*AppendToSeriesResponse)(nil), // 10: streamvis.v1.AppendToSeriesResponse
	nil,                            // 11: streamvis.v1.GetSeriesRequest.StructureEntry
}
var file_streamvis_v1_data_proto_depIdxs = []int32{
	11, // 0: streamvis.v1.GetSeriesRequest.structure:type_name -> streamvis.v1.GetSeriesRequest.StructureEntry
	7,  // 1: streamvis.v1.EncTyp.ival:type_name -> streamvis.v1.IntValues
	8,  // 2: streamvis.v1.EncTyp.fval:type_name -> streamvis.v1.FloatValues
	6,  // 3: streamvis.v1.AppendToSeriesRequest.field_vals:type_name -> streamvis.v1.EncTyp
	0,  // 4: streamvis.v1.Service.MakeOrGetScope:input_type -> streamvis.v1.GetScopeRequest
	2,  // 5: streamvis.v1.Service.DeleteScope:input_type -> streamvis.v1.DeleteScopeRequest
	4,  // 6: streamvis.v1.Service.MakeOrGetSeries:input_type -> streamvis.v1.GetSeriesRequest
	9,  // 7: streamvis.v1.Service.AppendToSeries:input_type -> streamvis.v1.AppendToSeriesRequest
	1,  // 8: streamvis.v1.Service.MakeOrGetScope:output_type -> streamvis.v1.GetScopeResponse
	3,  // 9: streamvis.v1.Service.DeleteScope:output_type -> streamvis.v1.DeleteScopeResponse
	5,  // 10: streamvis.v1.Service.MakeOrGetSeries:output_type -> streamvis.v1.GetSeriesResponse
	10, // 11: streamvis.v1.Service.AppendToSeries:output_type -> streamvis.v1.AppendToSeriesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_streamvis_v1_data_proto_init() }
func file_streamvis_v1_data_proto_init() {
	if File_streamvis_v1_data_proto != nil {
		return
	}
	file_streamvis_v1_data_proto_msgTypes[6].OneofWrappers = []any{
		(*EncTyp_Ival)(nil),
		(*EncTyp_Fval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamvis_v1_data_proto_rawDesc), len(file_streamvis_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamvis_v1_data_proto_goTypes,
		DependencyIndexes: file_streamvis_v1_data_proto_depIdxs,
		MessageInfos:      file_streamvis_v1_data_proto_msgTypes,
	}.Build()
	File_streamvis_v1_data_proto = out.File
	file_streamvis_v1_data_proto_goTypes = nil
	file_streamvis_v1_data_proto_depIdxs = nil
}
