#!/usr/bin/env python3

import fire
from bokeh.server.server import Server
from bokeh.application import Application
from bokeh.application.handlers.function import FunctionHandler
from streamvis import Server as SvServer

def main(rest_uri, run_name, bokeh_port=8000):
    def app_function(doc):
        sv_server = SvServer(doc, rest_uri, run_name)
        sv_server.start()

    handler = FunctionHandler(app_function)
    app = Application(handler)
    print(f'Serving on localhost:{bokeh_port}')
    bserver = Server({'/': app}, port=bokeh_port)
    bserver.start()
    bserver.io_loop.start()

fire.Fire(main)

