// compile from streamvis dir (repo directory)
// python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. streamvis/data.proto

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js"
// @generated from file streamvis/v1/data.proto (package streamvis.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ConfigRequest, ConfigResult, DataRequest, DataResult, DeleteTagRequest, DeleteTagResponse, NamesRequest, ScopeRequest, ScopeResult, Tag, WriteConfigRequest, WriteConfigResponse, WriteDataRequest, WriteDataResponse, WriteNameRequest, WriteNameResponse, WriteScopeRequest, WriteScopeResponse } from "./data_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service streamvis.v1.Service
 */
export const Service = {
  typeName: "streamvis.v1.Service",
  methods: {
    /**
     * @generated from rpc streamvis.v1.Service.QueryData
     */
    queryData: {
      name: "QueryData",
      I: DataRequest,
      O: DataResult,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc streamvis.v1.Service.Scopes
     */
    scopes: {
      name: "Scopes",
      I: ScopeRequest,
      O: ScopeResult,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc streamvis.v1.Service.Names
     */
    names: {
      name: "Names",
      I: NamesRequest,
      O: Tag,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc streamvis.v1.Service.Configs
     */
    configs: {
      name: "Configs",
      I: ConfigRequest,
      O: ConfigResult,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc streamvis.v1.Service.WriteScope
     */
    writeScope: {
      name: "WriteScope",
      I: WriteScopeRequest,
      O: WriteScopeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc streamvis.v1.Service.WriteConfig
     */
    writeConfig: {
      name: "WriteConfig",
      I: WriteConfigRequest,
      O: WriteConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc streamvis.v1.Service.WriteNames
     */
    writeNames: {
      name: "WriteNames",
      I: WriteNameRequest,
      O: WriteNameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc streamvis.v1.Service.DeleteScopeNames
     */
    deleteScopeNames: {
      name: "DeleteScopeNames",
      I: DeleteTagRequest,
      O: DeleteTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc streamvis.v1.Service.WriteData
     */
    writeData: {
      name: "WriteData",
      I: WriteDataRequest,
      O: WriteDataResponse,
      kind: MethodKind.Unary,
    },
  }
};

